### ISSUE TITLE
Error：Chinese-named of the Class name are not supported in version 5 of protégé（protégé5 无法显示中文的类名）

### ISSUE THREAD

**Issue by P-Zhu** [protegeproject/protege#818] opened 2018-12-28 10:34 UTC
Earlier：https://github.com/protegeproject/protege-distribution/issues/18
我下载的 protégé 5系列的所有程序包，在Windows10 Pro中都无法显示中文命名的类名！
换了多台电脑以及在虚拟机中安装全新Win10环境，同样无法正常显示 中文命名的类名。
-------------
Protégé 5.x cannot display Chinese-named of the class name in Windows10 Pro(1803)!
Changed many computers and installed a new Win10 environment in the virtual machine, as well cannot display Chinese-named of the class name.
--
**Since the Protégé  I downloaded does not support chinese-named class names, this test ontology file is created with Protege4.3 after [replacing "bin\felix. jar"](https://www.bbsmax.com/A/LPdoBq0w53/)**
--
Download the test Ontology：[Test Ontology.zip](https://github.com/protegeproject/protege-distribution/files/2743597/Test.Ontology.zip)
![owlviz](https://user-images.githubusercontent.com/33612712/50946164-30bf2900-14d3-11e9-94b5-7f991d269585.png)
![tim 20190110124254](https://user-images.githubusercontent.com/33612712/50946632-4f262400-14d5-11e9-849b-75a7fc93a44f.png)

**Comment by matthewhorridge** [comment] 2019-01-10 19:17
Duplicate of #824

**Closed by matthewhorridge** 2019-01-10 19:17 UTC
