### ISSUE TITLE
Invalid Turtle syntax with top-level blank node with no predicates and no objects

### ISSUE THREAD

**Issue by daiwt** [protegeproject/protege#775] opened 2018-04-13 06:40 UTC
As is mensioned in [this mail](http://protege-project.136.n4.nabble.com/Protege-saves-Turtle-files-in-invalid-syntax-td4655293.html), protege saves top-level blank node with a format that's valid in n3, but invalid in turtle.
```
# This is valid in N3, but invalid in Turtle
[ rdf:type owl:AllDisjointClasses ; 
  owl:members ( foo:Class1 
                foo:Class2 
              ) 
] .
```

```
# A valid Turtle syntax should be like this
[] rdf:type owl:AllDisjointClasses ; 
  owl:members ( foo:Class1 
                foo:Class2 
              ) .
```

I reproduced it with protege 5.2.0 platform-independent edition on Windows 10, and i believe it can be reproduced in other environments.

This may be ok with protege itself, but when I import the saved files on other platform, it may cause errors. For example, with Virtuoso, i got this message when i called the graph crud endpoint:

> SP029: TURTLE RDF loader, line 492: Missing predicate and object between top-level blank node subject and a dot processed pending to here.

**Comment by matthewhorridge** [comment] 2018-04-16 22:31
Serialization is delegate to the OWL API.  We need to figure out if updating the version of the OWL API that is used by Protege would fix this – if updating doesn't fix this then we'll file this as an OWL API issue.

**Comment by crapthings** [comment] 2018-06-10 14:06
@daiwt 

where can i set "owl:AllDisjointClasses" on protege view ?

**Comment by csnyulas** [comment] 2019-01-23 06:45
This seems to be working fine in Protege 5.5.0-beta-7 (after I added a prefix declaration for `foo`).

I would like to note that the first example given by the original poster (which I loaded both from a file called `test.ttl` and one called `test.n3`) was always loaded using the Turtle parser, never with the N3 parser. 

See relevant log entries below:

```
OWL API Version: 4.5.7.2018-12-02T02:23:35Z 
------------------------------- Loading Ontology ------------------------------- 
Loading ontology from file:/home/csnyulas/work/protege/test/turtle_vs_n3/test.ttl 
Finished loading file:/home/csnyulas/work/protege/test/turtle_vs_n3/test.ttl 
Loading for ontology and imports closure successfully completed in 296 ms 
Updated document format class from: org.semanticweb.owlapi.formats.RioTurtleDocumentFormat to: org.semanticweb.owlapi.formats.TurtleDocumentFormat 
 
---------------------------- Disposing of Workspace ---------------------------- 
Saved tab state for 'DL Query' tab 
Saved tab state for 'Entities' tab 
Saved tab state for 'Active Ontology' tab 
Saved tab state for 'Individuals by class' tab 
Saved workspace 
Disposed of 'DL Query' tab 
Disposed of 'Entities' tab 
Disposed of 'Active Ontology' tab 
Disposed of 'Individuals by class' tab 
Disposed of workspace 
 
------------------------------- Loading Ontology ------------------------------- 
Loading ontology from file:/home/csnyulas/work/protege/test/turtle_vs_n3/test.n3 
Finished loading file:/home/csnyulas/work/protege/test/turtle_vs_n3/test.n3 
Loading for ontology and imports closure successfully completed in 63 ms 
Updated document format class from: org.semanticweb.owlapi.formats.RioTurtleDocumentFormat to: org.semanticweb.owlapi.formats.TurtleDocumentFormat 
 
------------------------------- Loading Ontology ------------------------------- 
Loading ontology from file:/home/csnyulas/work/protege/test/turtle_vs_n3/valid.ttl 
Finished loading file:/home/csnyulas/work/protege/test/turtle_vs_n3/valid.ttl 
Loading for ontology and imports closure successfully completed in 63 ms 
Updated document format class from: org.semanticweb.owlapi.formats.RioTurtleDocumentFormat to: org.semanticweb.owlapi.formats.TurtleDocumentFormat 
 
```

**Comment by csnyulas** [comment] 2019-01-23 06:52
Just to make sure the issue is fully resolved it would be great if @daiwt could test the latest 5.5.0 beta (which can be downloaded from the Protégé website) with the examples that were causing problems before (and maybe even some new examples that could have been problematic in earlier versions).

This issue seems to be fixed, so unless we hear back otherwise, within a few days, we will close the issue.

**Comment by matthewhorridge** [comment] 2019-02-04 22:51
Looks good and closing due to no response.

**Closed by matthewhorridge** 2019-02-04 22:51 UTC
Labels: Status: Waiting to Close
