### ISSUE TITLE
Missing build number in About dialog

### ISSUE THREAD

**Issue by johardi** [protegeproject/protege#493] opened 2016-08-04 17:24 UTC
See screenshot below:
![screen shot 2016-08-04 at 10 21 34 am](https://cloud.githubusercontent.com/assets/5062950/17411551/9ff913ac-5a2d-11e6-878c-d5fbc5055cc4.png)

**Comment by matthewhorridge** [comment] 2016-08-04 21:35
Duplicate of #446

**Closed by matthewhorridge** 2016-08-04 21:35 UTC
