### ISSUE TITLE
URISyntaxException on loading an ontology

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#376] opened 2016-03-18 21:56 UTC
When I try to open the [dinner-start.owl.zip](https://github.com/protegeproject/protege/files/180447/dinner-start.owl.zip) ontology I get this URISyntaxException:

```
Level:       INFO
Time:        1458337292673
Message:     ------------------------------- Loading Ontology -------------------------------

Level:       INFO
Time:        1458337292674
Message:     Loading ontology from file:/home/csnyulas/Downloads/dinner-start.owl

Level:       ERROR
Time:        1458337292711
Message:     URI syntax error
java.net.URISyntaxException
StackTrace:  
    java.net.URI$Parser.fail(URI.java:2848)
    java.net.URI$Parser.checkChars(URI.java:3021)
    java.net.URI$Parser.parse(URI.java:3048)
    java.net.URI.<init>(URI.java:588)
    org.protege.editor.owl.model.library.folder.XmlBaseAlgorithm$MyHandler.startElement(XmlBaseAlgorithm.java:74)
    com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
    com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.startElement(XMLDTDValidator.java:745)
    com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1363)
    com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$ContentDriver.scanRootElementHook(XMLDocumentScannerImpl.java:1292)
    com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3138)
    com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:880)
    com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
    com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
    com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
    com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
    com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
    com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
    com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
    com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:333)
    javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
    org.protege.editor.owl.model.library.folder.XmlBaseAlgorithm.getSuggestions(XmlBaseAlgorithm.java:42)
    org.protege.editor.owl.model.library.folder.FolderGroupManager.examineSingleFile(FolderGroupManager.java:263)
    org.protege.editor.owl.model.library.folder.FolderGroupManager.examineDirectoryContents(FolderGroupManager.java:231)
    org.protege.editor.owl.model.library.folder.FolderGroupManager.update(FolderGroupManager.java:117)
    org.protege.editor.owl.model.library.OntologyCatalogManager.update(OntologyCatalogManager.java:158)
    org.protege.editor.owl.model.library.OntologyCatalogManager.ensureCatalogExists(OntologyCatalogManager.java:115)
    org.protege.editor.owl.model.library.OntologyCatalogManager.addFolder(OntologyCatalogManager.java:188)
    org.protege.editor.owl.model.OWLModelManagerImpl.addRootFolder(OWLModelManagerImpl.java:319)
    org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:274)
    org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:201)
    org.protege.editor.owl.OWLEditorKit.handleLoadRecentRequest(OWLEditorKit.java:189)
    org.protege.editor.core.ProtegeManager.openAndSetupRecentEditorKit(ProtegeManager.java:263)
    org.protege.editor.core.ui.action.OpenRecentAction$RecentEditorKitAction.openInNewWorkspace(OpenRecentAction.java:90)
    org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:224)
    org.protege.editor.core.ui.action.OpenRecentAction$RecentEditorKitAction.actionPerformed(OpenRecentAction.java:76)
    javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    java.awt.Component.processMouseEvent(Component.java:6525)
    javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    java.awt.Component.processEvent(Component.java:6290)
    java.awt.Container.processEvent(Container.java:2234)
    java.awt.Component.dispatchEventImpl(Component.java:4881)
    java.awt.Container.dispatchEventImpl(Container.java:2292)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    java.awt.Container.dispatchEventImpl(Container.java:2278)
    java.awt.Window.dispatchEventImpl(Window.java:2750)
    java.awt.Component.dispatchEvent(Component.java:4703)
    java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    java.awt.EventQueue.access$500(EventQueue.java:97)
    java.awt.EventQueue$3.run(EventQueue.java:702)
    java.awt.EventQueue$3.run(EventQueue.java:696)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    java.awt.EventQueue$4.run(EventQueue.java:724)
    java.awt.EventQueue$4.run(EventQueue.java:722)
    java.security.AccessController.doPrivileged(Native Method)
    java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

It may or may not be related to the fact that I just updated the [Snap SPARQL](https://github.com/protegeproject/snap-sparql-query) plugin to version 4.1.0.

**Comment by matthewhorridge** [comment] 2016-05-18 19:55
Not reproducible for me when loading directly from the URL or after downloading, unzipping and then loading.  

This looks like a problem with your catalog file.  Perhaps it is corrupt.

Closing for now.

**Closed by matthewhorridge** 2016-05-18 19:55 UTC
