### ISSUE TITLE
Null Pointer Exception when opening class expression editor

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#263] opened 2015-10-21 21:55 UTC
Once this exception is thrown, it is thrown continuously.

```
INFO  Starting Protege Desktop (Version 5.0.0, Build = beta-18-SNAPSHOT)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Platform:  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO      Java: JVM 1.8.0_60-b27 Memory: 954M  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO      Language: en, Country: US  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO      Framework: Eclipse (1.8.0)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO      OS: Linux (3.13.0)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO      Processor: x86-64  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Servlet API Bundle (3.1.0.v201410161800)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: JAXP XML (1.3.4.v201005080400)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: OSGi Release 4.2.0 Services (3.5.0.v20150519-2006)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Eclipse Registry Compatibility Fragment (3.6.0.v20150318-1505)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Apache Felix Gogo Runtime (0.10.0.v201209301036)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Eclipse Jobs Mechanism (3.7.0.v20150330-2103)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Equinox State and Resolver Compatibility Fragment (1.0.100.v20150402-1551)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Apache Felix Gogo Command (0.10.0.v201209301215)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Common Eclipse Runtime (3.7.0.v20150402-1709)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Apache Felix Gogo Shell (0.10.0.v201212101605)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Console plug-in (1.1.100.v20141023-1406)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Plugin: Extension Registry Support (3.6.0.v20150318-1503)  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	Servlet API Bundle Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	JAXP XML Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	OSGi Release 4.2.0 Services Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	Eclipse Registry Compatibility Fragment Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	Apache Felix Gogo Runtime Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	Equinox State and Resolver Compatibility Fragment Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	Apache Felix Gogo Command Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	Common Eclipse Runtime Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	Apache Felix Gogo Shell Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  	Console plug-in Plugin has no plugin.xml resource  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Using OWL API version 3.5.3.20150903-2211  org.protege.editor.owl.OWLEditorKit[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Rebuilding entity indices...  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  ... rebuilt in 5 ms  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Setting active ontology to OntologyID(OntologyIRI(<http://www.semanticweb.org/ttania/ontologies/2015/9/untitled-ontology-78>))  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Rebuilding entity indices...  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  ... rebuilt in 8 ms  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  ... active ontology changed  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Cannot generate ontology catalog for ontology at http://www.semanticweb.org/ttania/ontologies/2015/9/untitled-ontology-78  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Setting active ontology to OntologyID(OntologyIRI(<http://www.semanticweb.org/ttania/ontologies/2015/9/untitled-ontology-78>))  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Rebuilding entity indices...  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  ... rebuilt in 1 ms  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  ... active ontology changed  org.protege.editor.owl.model.OWLModelManagerImpl[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Auto-update last performed: Wed Oct 21 11:36:51 PDT 2015  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Auto-update has not been performed today.  Running it.  org.protege.editor.core.ProtegeApplication[Framework Event Dispatcher: Equinox Container: 00b1a85e-3d78-0015-1ea1-89f2556833c7]
INFO  Rebuilding search metadata cache...  org.protege.editor.owl.model.search.SearchManager[pool-1-thread-1]
INFO      ...rebuilt search metadata cache in 27 ms  org.protege.editor.owl.model.search.SearchManager[pool-1-thread-1]
INFO  Starting search 2 (pattern: \b(:?A)\b)  org.protege.editor.owl.model.search.SearchManager$SearchCallable[pool-1-thread-1]
INFO      finished search 2 in 6 ms (3 results)  org.protege.editor.owl.model.search.SearchManager$SearchCallable[pool-1-thread-1]
WARN  Error logged  org.protege.editor.core.ui.error.ErrorLog[AWT-EventQueue-0]
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.charAt(String.java:658)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxTokenizer.readChar(ManchesterOWLSyntaxTokenizer.java:228)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxTokenizer.tokenize(ManchesterOWLSyntaxTokenizer.java:125)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.<init>(ManchesterOWLSyntaxEditorParser.java:224)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.<init>(ManchesterOWLSyntaxEditorParser.java:178)
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLClassExpressionChecker.createObject(OWLClassExpressionChecker.java:38)
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLClassExpressionChecker.check(OWLClassExpressionChecker.java:33)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.isWellFormed(ExpressionEditor.java:198)
	at org.protege.editor.owl.ui.editor.OWLClassExpressionExpressionEditor.isValidInput(OWLClassExpressionExpressionEditor.java:49)
	at org.protege.editor.owl.ui.editor.OWLClassDescriptionEditor.isValidated(OWLClassDescriptionEditor.java:101)
	at org.protege.editor.owl.ui.editor.OWLClassDescriptionEditor.handleVerifyEditorContents(OWLClassDescriptionEditor.java:91)
	at org.protege.editor.owl.ui.editor.OWLClassDescriptionEditor.access$2(OWLClassDescriptionEditor.java:90)
	at org.protege.editor.owl.ui.editor.OWLClassDescriptionEditor$2.verifiedStatusChanged(OWLClassDescriptionEditor.java:55)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.notifyValidationChanged(ExpressionEditor.java:371)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.handleDocumentUpdated(ExpressionEditor.java:234)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.access$0(ExpressionEditor.java:230)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor$1.insertUpdate(ExpressionEditor.java:98)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.JTextPane.replaceSelection(JTextPane.java:192)
	at javax.swing.JTextPane.replaceSelection(JTextPane.java:175)
	at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
WARN  Uncaught Exception in thread AWT-EventQueue-0  org.protege.editor.core.ProtegeApplication$2[AWT-EventQueue-0]
java.lang.StringIndexOutOfBoundsException: String index out of range: 2
	at java.lang.String.charAt(String.java:658)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxTokenizer.readChar(ManchesterOWLSyntaxTokenizer.java:228)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxTokenizer.tokenize(ManchesterOWLSyntaxTokenizer.java:125)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.<init>(ManchesterOWLSyntaxEditorParser.java:224)
	at org.coode.owlapi.manchesterowlsyntax.ManchesterOWLSyntaxEditorParser.<init>(ManchesterOWLSyntaxEditorParser.java:178)
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLClassExpressionChecker.createObject(OWLClassExpressionChecker.java:38)
	at org.protege.editor.owl.ui.clsdescriptioneditor.OWLClassExpressionChecker.check(OWLClassExpressionChecker.java:33)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.isWellFormed(ExpressionEditor.java:198)
	at org.protege.editor.owl.ui.editor.OWLClassExpressionExpressionEditor.isValidInput(OWLClassExpressionExpressionEditor.java:49)
	at org.protege.editor.owl.ui.editor.OWLClassDescriptionEditor.isValidated(OWLClassDescriptionEditor.java:101)
	at org.protege.editor.owl.ui.editor.OWLClassDescriptionEditor.handleVerifyEditorContents(OWLClassDescriptionEditor.java:91)
	at org.protege.editor.owl.ui.editor.OWLClassDescriptionEditor.access$2(OWLClassDescriptionEditor.java:90)
	at org.protege.editor.owl.ui.editor.OWLClassDescriptionEditor$2.verifiedStatusChanged(OWLClassDescriptionEditor.java:55)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.notifyValidationChanged(ExpressionEditor.java:371)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.handleDocumentUpdated(ExpressionEditor.java:234)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor.access$0(ExpressionEditor.java:230)
	at org.protege.editor.owl.ui.clsdescriptioneditor.ExpressionEditor$1.insertUpdate(ExpressionEditor.java:98)
	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
	at javax.swing.JTextPane.replaceSelection(JTextPane.java:192)
	at javax.swing.JTextPane.replaceSelection(JTextPane.java:175)
	at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
WARN  Error logged  org.protege.editor.core.ui.error.ErrorLog[AWT-EventQueue-0]
java.lang.NullPointerException
	at javax.swing.text.FlowView$FlowStrategy.createView(FlowView.java:663)
	at javax.swing.text.FlowView$FlowStrategy.layoutRow(FlowView.java:520)
	at javax.swing.text.FlowView$FlowStrategy.layout(FlowView.java:477)
	at javax.swing.text.FlowView.layout(FlowView.java:201)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.text.BoxView.updateChildSizes(BoxView.java:366)
	at javax.swing.text.BoxView.setSpanOnAxis(BoxView.java:348)
	at javax.swing.text.BoxView.layout(BoxView.java:708)
	at javax.swing.text.BoxView.setSize(BoxView.java:397)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:912)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JEditorPane.getPreferredSize(JEditorPane.java:1332)
	at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:791)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validate(Container.java:1630)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
...

```

**Comment by matthewhorridge** [comment] 2016-05-18 18:02
Not able to reproduce this.  Closing for now.

**Closed by matthewhorridge** 2016-05-18 18:02 UTC
