### ISSUE TITLE
Wrong namespace setting (xmlns) when exporting in OWL/XML format

### ISSUE THREAD

**Issue by vincentvialard** [protegeproject/protege#289] opened 2015-12-08 09:17 UTC
Hi there,

I stumbled upon a small namespace problem using an ontology exported in OWL/XML by Protege 4.3. The `xmlns` setting is wrong:

```xml
<Ontology xmlns="http://www.w3.org/2002/07/owl#"
xml:base="http://www.derivo.de/namepace-test"
xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
xmlns:xml="http://www.w3.org/XML/1998/namespace"
ontologyIRI="http://www.derivo.de/namepace-test">
...
```
although it is correct in RDF/XML format:

```xml
<rdf:RDF xmlns="http://www.derivo.de/namepace-test#"
xml:base="http://www.derivo.de/namepace-test"
xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
xmlns:owl="http://www.w3.org/2002/07/owl#"
xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
...
```

Thanks for Protege!

Vincent.

**Comment by matthewhorridge** [comment] 2015-12-08 19:32
The default name space for the OWL/XML serialisation is the OWL namespace.  This is actually governed by the OWL API and is by design since all of the element names in this serialisation are from this namespace.

Can you provide some details as to how this causes you a problem?

**Comment by vincentvialard** [comment] 2015-12-08 19:47
Hi Matthew,

thanks for your fast reaction.

It caused problems to Ignazio (who is maintaining the OWLAPI) while he tried to analyze a problem I had found there [1].

All this world between the different paradigms is a bit obscure to me, but from what you write, the problem might be on his side. I'll post your answer on the OWLAPI-developer list.

Vincent.

[1] http://sourceforge.net/p/owlapi/mailman/message/34678197/

**Comment by matthewhorridge** [comment] 2015-12-08 19:51
Hi Vincent,

Thanks for the clarification.  I'll close this issue for now.

Matthew

**Closed by matthewhorridge** 2015-12-08 19:51 UTC
