### ISSUE TITLE
Error：The Class names Chinese-named  are not supported in Windows Pro(Running Protege-5.5.0-beta-7-win )（在Win10平台上Protege-5.5.0-beta-7-win 无法显示中文命名的类名）

### ISSUE THREAD

**Issue by P-Zhu** [protegeproject/protege#824] opened 2019-01-09 05:38 UTC
Protege-5.5.0-beta-7 cannot display  the class names Chinese-named  in Windows 10 Pro and Ubuntu!
---------------------------------------------------
我下载的 [Protege-5.5.0-beta-7-win.zip ](https://github.com/protegeproject/protege-distribution/releases/download/v5.5.0-beta-7/Protege-5.5.0-beta-7-win.zip)在Windows10 Pro中无法显示中文命名的类名！
换了多台电脑测试以及在虚拟机中安装全新Win10环境，都无法正常显示 中文命名的类名。
-----
Detail：
OS：Windows 10 Pro
OS Version：10.0.17134 Build 17134（1803）
OS Language：Simplified Chinese
Software Package：[Protege-5.5.0-beta-7-win.zip](https://github.com/protegeproject/protege-distribution/releases)

OS：Ubuntu
OS Descributor：Ubuntu 18.04.1 LTS
OS Language：Simplified Chinese
Software Package：[Protege-5.5.0-beta-7-linux.tar.gz](https://github.com/protegeproject/protege-distribution/releases)

![image](https://user-images.githubusercontent.com/33612712/51013002-28322580-159b-11e9-90cd-fbd1eb884364.png)
**Since the Protege5 I downloaded does not support chinese-named class names, this test ontology file is created with Protege4.3 after [replacing "bin\felix. jar"](https://www.bbsmax.com/A/LPdoBq0w53/)**
Download the test Ontology：[Test Ontology.zip](https://github.com/protegeproject/protege-distribution/files/2743597/Test.Ontology.zip)
![image](https://user-images.githubusercontent.com/33612712/51013231-57956200-159c-11e9-9e15-43fbc87557a9.png)

***********
Other(Protege-5.2.0-win.zip)：
![image](https://user-images.githubusercontent.com/33612712/51012834-36337680-159a-11e9-90a0-5e980a8fb65d.png)

**Comment by matthewhorridge** [comment] 2019-01-10 17:53
I've moved this issue into the main Protege repo

**Comment by csnyulas** [comment] 2019-01-10 19:12
I can reproduce this problem also in Ubuntu and P5.5 beta 5 (Linux version with JRE included):

![image](https://user-images.githubusercontent.com/2441046/50990998-77f3ec80-14c8-11e9-82bd-c45f714e9cde.png)


<br>

**Note:** At first I did not see the placeholder boxes, but rather the local name displayed:
![image](https://user-images.githubusercontent.com/2441046/50990386-be484c00-14c6-11e9-8117-f038cd75a8c0.png)

In order to see the Chinese labels (with the missing Chinese characters). I had to change the languages settings for the Annotation Renderer (`File -> Preferences... -> Renderer -> Entity Rendering -> Configure...`) from `en, en-US, !` to `en, en-US, zh, !`. Shouldn't the `!` stand for any further language? Or is it for no language tag specified? If this is a bug, we should create a separate issue for it.

**Comment by matthewhorridge** [comment] 2019-01-10 19:13
@csnyulas, for completeness, can you still reproduce this with the platform independent version?

**Comment by csnyulas** [comment] 2019-01-10 20:04
The same happens with the platform independent version as well (running it with Java 8, both oracle and openjdk). After I installed the language support libraries for Ubuntu, and also the specific once for both simplified and traditional Chinese, the class names in the view titles and breadcrumbs looked differently (a bit nicer, and more complicated, to my lay eyes), however the class names were still not shown in the class hierarchy as annotations values in class description view:

![image](https://user-images.githubusercontent.com/2441046/50993576-e471ea00-14ce-11e9-823c-7ce751a0f256.png)

My hunch is that, since in some parts of the UI, such as view titles and breadcrumbs, we do see the Chinese characters displayed properly, this is not a Java or OS problems, but rather some bug.

**Comment by matthewhorridge** [comment] 2019-01-14 23:42
I believe the above [commit](
https://github.com/protegeproject/protege/commit/4229813e521f4c76438cbfecd1298719b6777b60) fixes this issue.  We'll produce a beta-8 release soon and we'll wait for your feedback before closing this issue @P-Zhu

**Comment by matthewhorridge** [comment] 2019-01-17 17:06
@csnyulas I'm encouraged by the fact that it worked on Linux, when it didn't before.  @P-Zhu any chance you could take a look at this and let us know?

**Comment by P-Zhu** [comment] 2019-01-20 14:45
**Thank you very  much @matthewhorridge** 
Download the test Ontology：[Test Ontology.zip](https://github.com/protegeproject/protege-distribution/files/2743597/Test.Ontology.zip)
**Use the Protege-5.5.0-beta-8**
The problem has been solved with Windows 10  , but there are still some problems with the ubuntu platform(18.04 LTS )
![image](https://user-images.githubusercontent.com/33612712/51440657-74503900-1d04-11e9-90fb-ffd96e8d2b40.png)

**Comment by csnyulas** [comment] 2019-01-22 17:47
@P-Zhu please see the end of [my earlier comment](https://github.com/protegeproject/protege/issues/824#issuecomment-453217057) where I explain how I needed to change the rendering preferences in order to see the Chinese labels.

**Comment by matthewhorridge** [comment] 2019-01-24 17:41
@P-Zhu thanks for the feedback.  Good to know the problem has been solved for Windows.  We also believe that this problem is solved for Linux as it now works as expected on our machines here and a related bug to do with the display of ligatures over different platforms has been fixed.  

@csnyulas says, the rendering in your Linux screenshot is an artifact of the display preferences not being set up.

I'm therefore closing this issue.

**Closed by matthewhorridge** 2019-01-24 17:41 UTC
Labels: Status: Waiting to Close, Type: Critical Bug
