### ISSUE TITLE
Display of SKOS

### ISSUE THREAD

**Issue by marieALaporte** [protegeproject/protege#528] opened 2016-09-13 06:43 UTC
All the skos properties are displayed as annotation properties.
However, some of them are object properties: https://www.w3.org/TR/skos-reference/#semantic-relations

**Comment by matthewhorridge** [comment] 2016-09-13 22:10
Please can you give some steps to reproduce this?

**Comment by marieALaporte** [comment] 2016-09-14 07:09
The file I uploaded for test purposes:
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix ex: <http://www.products.com/>.
@prefix owl: <http://www.w3.org/2002/07/owl#>.

ex:Product rdf:type owl:Class;
  a skos:Concept;
  skos:prefLabel "Product"@en.

ex:Jewellery rdf:type owl:Class;
  a skos:Concept;
  skos:prefLabel "Jewellery"@en;
  skos:altLabel "Jewelry"@en;
  skos:altLabel "Jewelery"@en;
  skos:broader ex:Product.    

You see that the skos:broader is considered as annotation property
![protegeannotationtab](https://cloud.githubusercontent.com/assets/5664149/18502981/cb546a68-7a5a-11e6-9724-3cd3a82c95e9.png)

**Comment by matthewhorridge** [comment] 2016-09-16 20:46
This is because the OWL API, which Protege uses to parse this, doesn't have special parsing for SKOS vocabularies.  You will need to import the OWL-DL definition of SKOS:

http://www.w3.org/TR/skos-reference/skos-owl1-dl.rdf

I'll close this issue now.  Feel free to reopen it if you want us to investigate this further.

Here's your example with the import,

```ttl
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix ex: <http://www.products.com/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

ex:Ont a owl:Ontology .
ex:Ont owl:imports <http://www.w3.org/TR/skos-reference/skos-owl1-dl.rdf> .

ex:Product rdf:type owl:Class;
a skos:Concept;
skos:prefLabel "Product"@en.

ex:Jewellery rdf:type owl:Class;
a skos:Concept;
skos:prefLabel "Jewellery"@en;
skos:altLabel "Jewelry"@en;
skos:altLabel "Jewelery"@en;
skos:broader ex:Product.
```

**Closed by matthewhorridge** 2016-09-16 20:46 UTC

**Comment by egnargs** [comment] 2022-08-11 14:28
@matthewhorridge @marieALaporte How do you then apply the object property to the individual? For example, saying that the concept Ferrari is in the concept scheme of cars
