### ISSUE TITLE
Protege on Linux cannot load JSON-LD files with an HTTPS @context, but it works on macOS

### ISSUE THREAD

**Issue by gaurav** [protegeproject/protege#805] opened 2018-10-15 20:21 UTC
When loading JSON-LD files with a `@context` containing an HTTPS URL, I'm seeing different behavior on Protege 5.2.0 between macOS and Linux. I came up with two small test files at https://gist.github.com/gaurav/d685ee972ba738a0b9dd7c25b642f833 -- both the raw files can be loaded directly into Protege using its "Open from URL..." menu item.

On Protege 5.2.0 on macOS, both fails.jsonld and works.jsonld can be loaded correctly -- Protege reports an Annotation Property count of 1, which is `studyPublicationReference` with value `"Example"@xsd:string`. This is the expected behavior.

On Protege 5.2.0 on Linux, works.jsonld works the same way, but fails.jsonld has an Annotation Property count of 0, and the `studyPublicationReference` annotation is not loaded. Protege does not produce any errors. I notice that the Ontology IRI is unexpectedly set to `http://purl.obolibrary.org/obo/fails.jsonld`, while it is blank for works.jsonld.

I'm not sure if something is wrong with my JSON-LD file or if this is caused by a glitch in Protege or OWLAPI. If anybody has any clues as to why this is occurring or needs more information from me, please let me know. Thanks for your help!

**Comment by csnyulas** [comment] 2019-01-23 02:18
I successfully loaded both the `works.jsonld` and `fails.jsonld` ontologies in Protege 5.5-beta-7 on Ubunutu. First I downloaded both files, because I thought the problem is with the import (which still seems to be a problem and I'll add a separate comment about that). Then, I tried to open them from their URL.

Here is what I see if I load the two files from the disk:

![image](https://user-images.githubusercontent.com/2441046/51577205-e1cba900-1e6d-11e9-9502-80c6baef706a.png)

![image](https://user-images.githubusercontent.com/2441046/51577214-e98b4d80-1e6d-11e9-93b1-9ea03fb80220.png)

And here is what I see if I load them directly from the URL pointing to the raw gist:
`https://gist.github.com/gaurav/d685ee972ba738a0b9dd7c25b642f833/raw/9b3bf9ba1fb03f3e760e5e5cd1a96faa16154044/works.jsonld`

![image](https://user-images.githubusercontent.com/2441046/51578279-d1b5c880-1e71-11e9-81f9-2de934599943.png)

`https://gist.githubusercontent.com/gaurav/d685ee972ba738a0b9dd7c25b642f833/raw/9b3bf9ba1fb03f3e760e5e5cd1a96faa16154044/fails.jsonld`

![image](https://user-images.githubusercontent.com/2441046/51578294-df6b4e00-1e71-11e9-9734-9552300be5fa.png)

**Comment by matthewhorridge** [comment] 2019-01-24 17:36
@gaurav thanks for the excellent test case.  Would you mind trying this out with the latest 5.5.0-beta-8?  We've upgraded the OWL API, but I'm not sure this will make a difference in this case.

The ontology IRI of ```http://purl.obolibrary.org/obo/fails.jsonld``` is consistent with a failed parse because the OBO parser gobbles up anything and it's the last parser to be tried (which is unfortunate).

**Comment by matthewhorridge** [comment] 2019-02-04 22:53
Closing.  Will reopen if we hear further.

**Closed by matthewhorridge** 2019-02-04 22:53 UTC
Labels: Status: Waiting to Close, Type: Bug
