### ISSUE TITLE
open in new window dialogue incorrect behavior when tabbing through buttons

### ISSUE THREAD

**Issue by tgbugs** [protegeproject/protege#760] opened 2018-03-08 20:20 UTC
##### Steps:
1. ctrl-o or ctrl-shift-o
2. open in new window dialogue appears
3. hit tab and switch selected box to `No` (highlighted in orange)
4. hit enter

##### Actual results:
The `Yes` button visually depresses and the ontology opens in the same window.

##### Expected results:
The `No` button should depress and the ontology should open in a new window.

**Comment by csnyulas** [comment] 2018-03-08 21:34
It works if you use the `SPACE` key (instead of `ENTER`) to confirm your selection.

This is something very low level functionality of a swing component, that we don't have much control over. I suspect that the behavior really depends on your OS. I was able to reproduce it on Ubuntu.

Since this is a swing issue, I don't think we will be able to fix this. We'll look into possible solutions on the web, before closing it, though.

**Comment by tgbugs** [comment] 2018-03-08 23:10
Thanks for the space workaround!

**Closed** 2019-01-15 16:49 UTC
