### ISSUE TITLE
Save As... progress bar does not disappear

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#576] opened 2016-10-25 07:42 UTC
Trying to save a new ontology using the `File -> Save As...` menu brought up a dialog box that showed a progress bar. The progress bar hung at approx 20% and the dialog did not disappear, although the file seemed to have been saved on the disk, and I was able to continue to use Protege further. Next time I tried to save the ontology in a file with a different name, the old dialog appeared and nothing has changed (see screen shot below).

I don't know if it has any relevance, but I had different version of the same ontology (i.e. sharing the same ontology IRI) opened in three separate Protege workspaces.

![screenshot protege save as progress does not close](https://cloud.githubusercontent.com/assets/2441046/19676670/77061ea6-9a4a-11e6-9c00-afab7c76c34e.png)

Observed in Protege 5.1.0, on Ubuntu.

**Comment by donpellegrino** [comment] 2016-10-26 15:41
This appears to be a duplicate of issue #574

**Comment by matthewhorridge** [comment] 2019-01-15 20:56
Yep duplicate.  Closing this as #574 has more info (and I think has been fixed).

**Closed by matthewhorridge** 2019-01-15 20:56 UTC
