### ISSUE TITLE
Rule editor can't deal with prefixed names properly (including with "swrlb:")

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#660] opened 2017-06-16 18:52 UTC
The [Rule editor](https://github.com/protegeproject/protege/blob/master/protege-editor-owl/src/main/java/org/protege/editor/owl/ui/editor/SWRLRuleEditor.java) does not seem to be able to parse prefixed names. It also does not recognize the `swrlb:` prefix. For example one can write a rule like this:
```A(?i), add(?x, 2, 2) -> prop1(?i, ?x)```
which would be parsed correctly and interpreted correctly by reasoners, but if you try to edit this rule again it will be displayed as
``` A(?i), swrlb:add(?x, 2, 2) -> prop1(?i, ?x)```
and the `swrlb:add` part will be highlighted in red, as being invalid.

Other prefixed names also seem to be highlighted as invalid.

This problem is described also on the mailing list:
http://protege-project.136.n4.nabble.com/Tricky-Problems-of-Rules-Tab-and-SWRLTAB-td4668823.html

**Comment by csnyulas** [comment] 2019-01-25 08:13
Just tested this in latest 5.5.0 beta (9 snapshot). 
It may be indeed confusing that the "Rules" does not take the `swrlb:` prefix and the "SWRLTab" works only if the `swrlb:`prefix is used before the SWRL built-in names. However, the behavior of each view is consistent with itself, and a rule specified in one view will be properly transcribed in the other view.

I am not sure if we want to do anything about this, or if there is anything that could be done to provide a better user experience.

**Comment by matthewhorridge** [comment] 2019-01-25 17:03
Prefixed names should be consistent throughout Protege and depend upon the rendering settings.  Closing this because it's the intended behaviour.

**Closed by matthewhorridge** 2019-01-25 17:03 UTC
Labels: Status: Reproduced, Type: Bug
