### ISSUE TITLE
Protege GUI apparently displaying in absent display monitor in Windows 10

### ISSUE THREAD

**Issue by samsontu** [protegeproject/protege#804] opened 2018-10-13 23:58 UTC
On Oct 13, 2018, at 12:00 PM, Campbell, James R <campbell@unmc.edu> wrote:

I have a problem with Protege-Windows interaction.  At home I use a two screen system and in recent history the command prompt screen for Protege launched on screen 1 and I moved the client to window 2 for readability.  I went on the road and did a demo but had only screen 1 functional, screen 2 was back home.   Protege launched with the command screen visible on the monitor but the Protege client was not accessible.  It clearly showed as an active session on the task bar but when I alt-tabbed to that session, it clearly seemed to be presenting in virtual reality on the absent screen 2.  When I got home I tried configuring windows 10 only for screen 1 display, but get the same behavior EVEN AFTER reinstalling the Protege 5.5.3 software.  I cannot access preferences or any other client features.  No other windows software behaves this way

**Comment by samsontu** [comment] 2018-10-14 00:00
A workaround is described in:

**Comment by csnyulas** [comment] 2019-01-16 01:36
This problem I could reproduce also in Ubuntu with the currently latest P5.5-beta-8.

**Comment by csnyulas** [comment] 2019-01-16 04:39
Indeed, d32f8e0 seems to have fixed this issue. I cannot reproduce it anymore in P5.5-beta-9 snapshot.

**Comment by csnyulas** [comment] 2019-01-16 04:41
If it works on Windows also, we can close this issue.

**Closed** 2019-01-16 04:56 UTC
Labels: Status: Fixed, Type: Bug
