### ISSUE TITLE
Protege 5.00 freezes when opening SPARQL tab

### ISSUE THREAD

**Issue by BernhardHumm** [protegeproject/protege#392] opened 2016-04-18 09:00 UTC
I installed Protege 5.00 (Build beta 23) under Windows 10.
I can open an ontology and search without any problems.
However, when I try to open the SPARQL tab, the whole application freezes for about 5 minutes (on a new notebook).
After this long waiting period, everything seems to work fine.

Any help?
P.S. Reasoner is set off.
No import of old preferences in "HKEY_CURRENT_USER\Software\JavaSoft\Prefs\/P/R/O/T/E/G/E_/P/R/E/F/E/R/E/N/C/E/S\ 

Regards
        Bernhard

**Comment by tudorache** [comment] 2016-04-18 21:59
SPARQL plugin issues should be reported here:
https://github.com/protegeproject/sparql-query-plugin/issues/

This issue seems like duplicate of: 
https://github.com/protegeproject/sparql-query-plugin/issues/5

Workaround: use the SNAP SPARQL Plugin, which you can get from the auto-update: File menu -> Check for plugins. Once installed, the view plugin can be added from: Window menu -> Views -> Query views -> Snap SPARQL.

Closing this issue.

**Closed by tudorache** 2016-04-18 21:59 UTC
