### ISSUE TITLE
Asserted hierarchy is not displayed correctly in some cases when equivalent named classes are present

### ISSUE THREAD

**Issue by nicolevasilevsky** [protegeproject/protege#847] opened 2019-02-05 02:56 UTC
This is just an issue for me with [Cell Ontology](https://github.com/obophenotype/cell-ontology), not any other ontology, and it seems to be an issue with different versions of Protege, I am currently using v5.5.0 beta.

When I search for a class, and click on it in the search box, it will bring up the annotations, but it won't pull up the class in the Class hierarchy pane.

Here is a screenshot, you can see that native cell is not displayed in the Class Hierarchy pane:
![image](https://user-images.githubusercontent.com/6722114/52250837-92926900-28ae-11e9-8970-ea2d9eb0d1fc.png)

Thanks for looking into this. Let me know if you need any other info.

**Comment by csnyulas** [comment] 2019-02-05 05:01
Actually, to me it seems that 'native cell' is, in fact, selected in the class hierarchy view, as it is displayed in the title of the view: **Class hierarchy: 'native cell'**. I expect that if you would scroll down, you would probably see the selection. If this is the case, then the real problem is that the class hierarchy view does not automatically scroll the content of the view as to show the newly selected entity. At least not always. Can you confirm that this is indeed the problem?

**Comment by nicolevasilevsky** [comment] 2019-02-05 17:14
Hi @csnyulas, unfortunately that is not the case, I don't see the class if I scroll.

**Comment by matthewhorridge** [comment] 2019-02-05 17:14
Hi @nicolevasilevsky!

I've just had a look at this...

I loaded CL from https://raw.githubusercontent.com/obophenotype/cell-ontology/master/cl.owl and then switched to the entities tab and performed a search for 'native cell'.  The hierarchy expanded and 'native cell' became selected.

What I notice though, is that my hierarchy looks like this:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/488607/52290941-1cc9e400-2926-11e9-921e-ab8a1d18b64b.png">

You only have 'abnormal cell' under 'cell' in your screenshot.  I have two cell classes, one from CL (CL:0000000) and one from GO (GO:0005623).  I therefore think it's possible that I've loaded a different ontology and imports closure to you.  Please would you be able to double check the URL for me?

Thanks a lot!

**Comment by matthewhorridge** [comment] 2019-02-05 17:22
@nicolevasilevsky I've cloned the repo and I'll open cell-edit.owl (sorry, didn't see this before!)

**Comment by matthewhorridge** [comment] 2019-02-05 17:23
@nicolevasilevsky I can reproduce this, will look into it and thanks for the bug report!

**Comment by nicolevasilevsky** [comment] 2019-02-05 18:18
Hi @matthewhorridge! Thanks for looking into this - it is a really weird bug!

**Comment by matthewhorridge** [comment] 2019-02-05 22:53
Definitely a weird bug with the hierarchy! Basically the issue was that CL cell is equivalent to GO cell and Protege arbitrarily just displayed GO cell.  I think I've fixed this problem....

Now both cell classes are displayed.  See the screenshot below.  

Where a short name/label maps into multiple terms I've added disambiguation by including the OBO Id in brackets.  @nicolevasilevsky do you think this is a good idea or does it add too much clutter?  @cmungall, any thoughts about this?

<img width="354" alt="image" src="https://user-images.githubusercontent.com/488607/52309393-d93a9e80-2954-11e9-834a-598e2b9e779d.png">

and without the equivalences displayed (perhaps these are unnecessary)

<img width="302" alt="image" src="https://user-images.githubusercontent.com/488607/52309683-c96f8a00-2955-11e9-9370-3191c649b46f.png">

**Comment by nicolevasilevsky** [comment] 2019-02-05 23:05
I love it - this is great!

**Comment by matthewhorridge** [comment] 2019-02-05 23:47
Great.  I've just pushed the fix so this will be available in the next beta release (or candidate release)

**Comment by nicolevasilevsky** [comment] 2019-02-05 23:49
Awesome, thank you so much!

**Comment by cmungall** [comment] 2019-02-06 01:42
this is great, thanks!

**Comment by matthewhorridge** [comment] 2019-02-06 03:20
Just another follow up to this.  For single entity names, I'm experimenting with disambiguation in the class description view too.  So the view for CL cell would be

<img width="455" alt="image" src="https://user-images.githubusercontent.com/488607/52318740-c3d86b00-297a-11e9-9615-91787f215ac3.png">

Here "cell" and "anatomical structure" are disambiguated because this label maps to multiple entities.  Unambiguous entries aren't disambiguated. 

Any thoughts?

**Comment by addiehl** [comment] 2019-02-06 13:05
Thanks Matthew for fixing this!

**Closed** 2019-03-08 22:39 UTC
Labels: Status: Fixed, Type: Bug
