### ISSUE TITLE
Better font support for high resolution displays

### ISSUE THREAD

**Issue by tudorache** [protegeproject/protege#448] opened 2016-06-10 04:33 UTC
The default font on high resolution displays is too small to read. Even when increasing the font size, the font of the menus and other actions is not increased. Also, the height of the items in the frame list does not seem to adjust properly.

Reported on the mailing list:

I confirm the behaviour on a Windows 10 Microsoft Surface Book (3000 x 2000
pixel -> high dpi)

First picture shows the default font size 12.
<http://protege-project.136.n4.nabble.com/file/n4665566/Protege_font_12.png> 

The second picture with size 38
<http://protege-project.136.n4.nabble.com/file/n4665566/Protege_font_38.png> 

Neither of them is realy readable

**Comment by matthewhorridge** [comment] 2016-06-10 10:57
This is a duplicate of #115.  Basically, this isn't a Protege problem per se, but a Java/Swing issue on Windows and High Res displays.  I need to have a look at possible solutions.

I've separated out the issue of the metrics view not respecting font size settings into a new issue: https://github.com/protegeproject/protege/issues/449.

**Closed by matthewhorridge** 2016-06-10 10:57 UTC

**Comment by MMMMQQQQ** [comment] 2019-02-12 21:05
I have solved the problem by decrease the resolution of my windows 10 (originally it is 3840*2160, after changed, it is 1600*900)

**Comment by fshaker** [comment] 2020-01-28 11:06
I am having the same problem. This is problem happens with some other applications too. The solution can be found here:
https://superuser.com/questions/1056631/fonts-extremely-small-in-some-applications-windows-10

**Comment by febikamMck** [comment] 2022-08-15 21:03
> I had the same problem. This problem happens with some other applications too. I could solve the problem using the solution presented here: https://superuser.com/questions/1056631/fonts-extremely-small-in-some-applications-windows-10

This fixed my issue. Thnx @fshaker
