### ISSUE TITLE
Slow ontology loading on Windows 10

### ISSUE THREAD

**Issue by kodymoodley** [protegeproject/protege#826] opened 2019-01-12 12:50 UTC
The attached ontology (30KB) loads instantly in Protege 5.2 but is extremely slow to load in Protege 5.5.0-beta-4 and Protege 5.5.0-beta-7

I'm on Windows 10 (16GB RAM) and i'm using the bundled JREs (v1.8.0_40) with these releases.
[ontologymarble.zip](https://github.com/protegeproject/protege/files/2751995/ontologymarble.zip)

**Comment by kodymoodley** [comment] 2019-01-16 21:07
Hi @matthewhorridge, indeed that is the issue. It loads fast when in a directory by itself (and also with one or two other .owl files, and one sub-directory). Thanks!

**Comment by csnyulas** [comment] 2019-01-16 21:36
Closing this issue as it is duplicate of #83.

**Closed by csnyulas** 2019-01-16 21:36 UTC
Labels: Status: Waiting for Feedback
