### ISSUE TITLE
Problems with creating class hierarchy from tab-indented text

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/protege#599] opened 2017-01-10 08:53 UTC
Reported on the protege-user mailing list on 01/09/2017:

I'm using Protege for the first time, version 5.1.0 on Max OSX (El Capitan).
I'm trying to follow the pizza tutorial, which is a little outdated, but
still intelligible.

When I come to creating a class hierarchy from tab-indented text, Protege
does the wrong thing. E.g, if I enter:

-------------
A
(tab)B
(tab)(tab)C
(tab)(tab)(tab)D
------------

I get a class hierarchy that looks like this:

owl::Thing
|
+-C
|   L_ D
|
+-B
|  L_ C
|
+-A
|
+-A
   L_B

in case that doesn't render clearly, let me re-state the hierarchy I get
like this:
owl:Thing -> C -> D
owl:Thing -> B -> C
owl:Thing -> A
owl:Thing -> A -> B

I've even tried loading the pizza.owl file, using the 'Copy sub-hierarchy as
tab indented text' function, loading a new model, and pasting that text back
into the 'create class hierarchy' box. I get the same result.

Am I doing something wrong, or is this a known problem?

**Comment by matthewhorridge** [comment] 2017-01-10 10:28
I'm not able to reproduce this.  I entered the hierarchy as described above and got the expected (correct) result.  I'm also testing with 5.1.0 on El Capitan.  

Can the original poster provide a text file with the hierarchy that causes the problem?

**Comment by Wildish-LBL** [comment] 2017-01-10 18:09
Hi,

attached is the original pizza.owl that I used (named as pizza.owl.txt so that github will accept the upload). I copy the entire class hierarchy as tab-indented text, which I save in pizza.txt (also attached). You can see that pizza.txt is indeed a tab-delimited file.

I then quite Protege, and restart it, with a clean session. I go to the Entities tab, select owl:Thing, and 'Add Subclasses', pasting in exactly the text I just copied. Moving the cursor around in the input window, I do indeed see that the whitespace is still tabs, not spaces. The result is a messed-up hierarchy, as you can see from the screenshot.

I've tried this with and without the 'make siblings disjoint' option, it makes no difference.

I have a screen recording of the process in action if you want it, but it's 115 MB, and github won't let me upload it, it has a 10 MB limit.

This isn't specific to this file, I can also create a trivial hierarchy owl:Thing -> A -> B -> C -> D which shows exactly the same behaviour.

For completeness, the owl and txt file checksums are:
1718924641 126940 pizza.owl.txt
2370433685 1896 pizza.txt

[pizza.owl.txt](https://github.com/protegeproject/protege/files/696932/pizza.owl.txt)
[pizza.txt](https://github.com/protegeproject/protege/files/696933/pizza.txt)
![protege-messed-up-hierarchy](https://cloud.githubusercontent.com/assets/20309342/21818406/90f9a92c-d71c-11e6-95d6-811df6f4fba1.png)

Thanks for the help!

**Comment by csnyulas** [comment] 2017-01-12 05:49
As you can see in this half minute long video, following the exact steps that you described worked fine for me fine:
https://youtu.be/zkdyj1Y2tZ4

However, looking more carefully at your screen shot, I observed that you have rdfs:labels specified for your created classes, and that their IRIs end with some random strings of characters. So, I tried to import a class hierarchy, after I changed the new entity settings in Protege to auto-generate ids, and, indeed, **I was able to reproduce the bug**, as you can see it here:
https://youtu.be/sZChWU31iAc

In the below screen shot you can see that after forcing Protege to reorder all classes alphabetically (`Window -> Refresh user interface`), there are many "duplicate" top level classes (such as `CheeseTopping`, `DomainConcept`, `FishTopping`, `Pizza`, `NamedPizza`), in fact exactly as many as the number of class-subclass relationships present in the imported tab delimited text:
![image](https://cloud.githubusercontent.com/assets/2441046/21878342/6f64a368-d846-11e6-9c09-fe31da92103e.png)

**Comment by matthewhorridge** [comment] 2017-01-12 10:26
Good detective work.  I'll look into a fix for this.

**Comment by Wildish-LBL** [comment] 2017-01-12 18:06
Hi,

I confirm that disabling auto-generated IDs fixes the problem for me too. Well spotted, and thanks for the quick workaround!

Cheers,
Tony.

**Closed** 2017-02-10 19:30 UTC
Labels: bug

**Comment by Lemon-Liu** [comment] 2017-07-31 11:06
I also met this problem just exactly like @Wildish-LBL ! 
and I want to know whether it is fixed. 
Plus,  I still met this problem when I tried the latest version(5.2)~
